sudo: required
language: generic
services: 
  - docker

before_install:
  # Login to the Docker Cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker build -t rajat7813/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rajat7813/react-test npm test

after_success:
  - docker build -t rajat7813/multi-client ./client
  - docker build -t rajat7813/multi-nginx ./nginx
  - docker build -t rajat7813/multi-server ./server
  - docker build -t rajat7813/multi-worker ./worker
  # Login to the Docker Cli
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push rajat7813/multi-client
  - docker push rajat7813/multi-nginx
  - docker push rajat7813/multi-server
  - docker push rajat7813/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-573784929197'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY